FourSeasons/Controllers/Admin/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FourSeasons.Controllers.Admin
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FourSeasons/Controllers/Guest/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FourSeasons.Models;
using FourSeasons.dbContexts;

namespace FourSeasons.Controllers.Guest
{
    public class BookingController : Controller
    {
        private readonly FourSeasonsContext _context;
        private BookingVM model;

        public BookingController(FourSeasonsContext context)
        {
            model = new BookingVM();
            _context = context;
        }

        public IActionResult Index()
        {
            model.RoomList = getRooms();
            model.TotalPrice = _context.TotalPriceSet.Find(1).Value;
            _context.TotalPriceSet.Find(1).Value = 0;
            _context.SaveChanges();
            return View(model);
        }


        public IActionResult ChooseAction(Room model, string action, DateTime _startDate, DateTime _finishDate, string _name, string _email)
        {
            if (action == "getCost")
            {
                getCost(model, _startDate, _finishDate);
            }
            else if (action == "Book")
            {
                Book(model, _startDate, _finishDate, _name, _email);
            }

            return RedirectToAction("Index");
        }



        private IActionResult getCost(Room model, DateTime _startDate, DateTime _finishDate)
        {
            _context.TotalPriceSet.Find(1).Value = (int)calculateCost(model, _startDate, _finishDate);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        private double calculateCost(Room model, DateTime _startDate, DateTime _finishDate)
        {
            double cost = 0;
            double seaview = 0;
            double balcon = 0;
            double price = 0;
            double bar = 1500;

            while (!_startDate.Date.Equals(_finishDate.Date))
            {
                switch (model.Type)
                {
                    case "Одноместный": price = 2000; break;
                    case "Двухместный": price = 3500; break;
                    case "Четырехместный": price = 5000; break;
                    case "Мансарда": price = 3000; break;
                }

                if (model.SeaView == true)
                {
                    seaview = price * 0.2;
                }

                if (model.Balcon == true)
                {
                    balcon = price * 0.15;
                }

                cost += price + seaview + balcon;

                _startDate = _startDate.AddDays(1);
            }

            if (model.Bar == true)
            {
                cost += bar;
            }

            return cost;
        }



        private IActionResult Book(Room model, DateTime _startDate, DateTime _finishDate, string _name, string _email)
        {
            _context.BookingSet.Add(new Booking
            {
                Name = _name,
                Email = _email,
                Type = model.Type,
                SeaView = model.SeaView,
                Balcon = model.Balcon,
                Bar = model.Bar,
                TotalPrice = (int)calculateCost(model, _startDate, _finishDate),
                StartDate = _startDate,
                FinishDate = _finishDate
            });

            _context.SaveChanges();
            return RedirectToAction("Index");
        }



        private List<Room> getRooms()
        {
            List<Room> roomsList = new List<Room>();

            foreach (Room element in _context.RoomsSet)
                roomsList.Add(element);

            return roomsList;
        }

        
        
     
    }
}

FourSeasons/Controllers/Guest/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FourSeasons.Models;
using FourSeasons.dbContexts;

namespace FourSeasons.Controllers.Guest
{
    public class FoodController : Controller
    {
        private readonly FourSeasonsContext _context;

        public FoodController(FourSeasonsContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(GetFood());
        }

        private List<Food> GetFood()
        {
            List<Food> foodList = new List<Food>();

            foreach (Food element in _context.FoodSet)
                foodList.Add(element);

            return foodList;
        }
    }
}

FourSeasons/Controllers/Guest/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FourSeasons.Models;
using FourSeasons.dbContexts;

namespace FourSeasons.Controllers.Guest
{
    public class RoomsController : Controller
    {
        private readonly FourSeasonsContext _context;

        public RoomsController(FourSeasonsContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(getRooms());
        }

        private List<Room> getRooms()
        {
            List<Room> roomsList = new List<Room>();

            foreach (Room element in _context.RoomsSet)
                roomsList.Add(element);

            return roomsList;
        }
    }
}

FourSeasons/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FourSeasons</title>
    <script type="text/javascript" src="~/js/validator.js"></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/layout.css" />
        <link rel="stylesheet" href="~/css/menu.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <div class="body-all-container">
        <nav class="menu">
            <div class="menu-container">
                <div class="menu-hotelname-container">
                    <div class="menu-hotelname">
                        <a asp-area="" asp-controller="Admin" asp-action="Index">Раздел aдминистратора</a>
                    </div>
                </div>

                <div class="menu-list-container-admin">
                    <ul class="menu-list">
                        <li><a asp-area="" asp-controller="NewsAdmin" asp-action="Index">Новости</a></li>
                        <li><a asp-area="" asp-controller="GalleryAdmin" asp-action="Index">Галерея</a></li>
                        <li><a asp-area="" asp-controller="CommentsAdmin" asp-action="Index">Отзывы</a></li>
                        <li><a asp-area="" asp-controller="ContactsAdmin" asp-action="Index">Контакты</a></li>
                        <li><a asp-area="" asp-controller="BookingAdmin" asp-action="Index">Бронирование</a></li>
                        <li><a asp-area="" asp-controller="FoodAdmin" asp-action="Index">Питание</a></li>
                        <li><a asp-area="" asp-controller="ComfortAdmin" asp-action="Index">Услуги и удобства</a></li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="body-content-container">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - FourSeasons</p>
            </footer>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

FourSeasons/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FourSeasons</title>
    <script type="text/javascript" src="~/js/validator.js"></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/layout.css" />
        <link rel="stylesheet" href="~/css/menu.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>

<body>


    <div class="body-all-container">
        <nav class="menu">
            <div class="menu-container">
                <div class="menu-hotelname-container">
                    <div class="menu-hotelname">
                        <a asp-area="" asp-controller="Home" asp-action="Index">FourSeasons</a>
                    </div>
                </div>

                <div class="menu-list-container">
                    <ul class="menu-list">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Главная</a></li>
                        <li>
                            <a asp-area="" asp-controller="Hotel" asp-action="Index" style="pointer-events: none;">Об отеле</a>
                            <ul class="submenu">
                                <li><a asp-area="" asp-controller="Gallery" asp-action="Index">Галерея</a></li>
                                <li><a asp-area="" asp-controller="Comfort" asp-action="Index">Услуги и удобства</a></li>
                                <li><a asp-area="" asp-controller="Contacts" asp-action="Index">Контакты</a></li>
                                <li><a asp-area="" asp-controller="Comments" asp-action="Index">Отзывы</a></li>
                            </ul>
                        </li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact" style="pointer-events: none;">Номера</a>
                            <ul class="submenu1">
                                <li><a asp-area="" asp-controller="Rooms" asp-action="Index">Просмотр номеров</a></li>
                                <li><a asp-area="" asp-controller="Booking" asp-action="Index">Бронирование</a></li>
                            </ul></li>
                        <li><a asp-area="" asp-controller="Food" asp-action="Index">Питание</a></li>
                        <li><a asp-area="" asp-controller="SiteMap" asp-action="Index">Карта сайта</a></li>

                    </ul>
                </div>
            </div>
        </nav>
        <link rel="stylesheet" href="~/css/carousel.css" />

        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/images/slider/banner1.jpg" class="img-responsive" />
                    <div class="carousel-caption">
                        <p>
                            Добро пожаловать на веб-сайт отеля FourSeasons
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="~/images/slider/banner2.jpg" class="img-responsive" />
                    <div class="carousel-caption">
                        <p>
                            Люкс номера с видом на море по приятой цене
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="~/images/slider/banner3.jpg" class="img-responsive" />
                    <div class="carousel-caption">
                        <p>
                            Огромные бассейны, SPA, русская баня и тайский массаж
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="~/images/slider/banner4.jpg" class="img-responsive" />
                    <div class="carousel-caption">
                        <p>
                            Профессиональный бар и авторская кухня
                        </p>
                    </div>
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>


        <div class="body-content-container">
            @RenderBody()
            <footer>
                <p>&copy; 2018 - FourSeasons</p>
            </footer>
        </div>
    </div>



    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
        </html>