FourSeasons/Controllers/Admin/NewsAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FourSeasons.Models;
using FourSeasons.dbContexts;

namespace FourSeasons.Controllers.Admin
{
    public class NewsAdminController : Controller
    {
        private readonly FourSeasonsContext _context;

        public NewsAdminController(FourSeasonsContext context)
        {
            _context = context;
        }

        [Route ("Admin/News")]
        public IActionResult Index()
        {
            return View(getNews());
        }

        [HttpPost]
        public ActionResult Update(News news)
        {
            _context.Entry(news).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(News news)
        {
            _context.NewsSet.Remove(_context.NewsSet.Find(news.Id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Add(string _header, string _content, string _imgLink)
        {           
            _context.NewsSet.Add(new News { Header = _header, Content = _content, ImgLink = _imgLink, Date = DateTime.Now});
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        private List<News> getNews()
        {
            List<News> newsList = new List<News>();

            foreach (News element in _context.NewsSet)
                newsList.Add(element);

            return newsList;
        }
    }
}

FourSeasons/Views/NewsAdmin/Index.cshtml
@model List<News>
@{
    ViewData["Title"] = "Новости";
}
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link rel="stylesheet" href="~/css/admin-news.css" />

<div class="content">
    <div class="content-admin-news">

        <div class="news-add">
            <p>Добавить новость</p>
            @using (Html.BeginForm("Add", "NewsAdmin", FormMethod.Post))
            {
                
                <input type="text" name="_header" placeholder="Заголовок" id="name" maxlength="45"/><br />
                <textarea name="_content" placeholder="Текст (не более 500 символов)" id="textarea" maxlength="500"></textarea><br />
                <input type="text" name="_imgLink" placeholder="Полное название файла изображения" id="image"/><br />

                <input type="submit" value="Добавить" onclick="return validateAddNewsForm('name', 'textarea', 'image');"/>
            }
        </div>
        

        @for (int i = Model.Count - 1; i >= 0; i--)
        {
            <div class="news-container">

                @using (Html.BeginForm("Update", "NewsAdmin", FormMethod.Post))
                {
                    @Html.HiddenFor(Model => Model.ElementAt(i).Id)<br />
                    <input class="text-box single-line" id=@string.Format("name{0}", Model.ElementAt(i).Id.ToString()) name="Header" type="text" placeholder="Заголовок" value="@Model.ElementAt(i).Header" maxlength="45"/><br />
                    <textarea class="text-box multi-line" id=@string.Format("textarea{0}", Model.ElementAt(i).Id.ToString()) name="Content" placeholder="Текст (не более 500 символов)" maxlength="500">@Model.ElementAt(i).Content</textarea><br />
                    <input class="text-box single-line" id=@string.Format("image{0}", Model.ElementAt(i).Id.ToString()) name="ImgLink" placeholder="Полное название файла изображения" value="@Model.ElementAt(i).ImgLink" type="text"><br />
                    @Html.HiddenFor(Model => Model.ElementAt(i).Date)<br />

                            
                    <div class="news-upd-btn-container"><input type="submit" value="Сохранить изменения" onclick="return validateAddNewsForm('name' + '@Model.ElementAt(i).Id.ToString()', 'textarea' + '@Model.ElementAt(i).Id.ToString()', 'image' + '@Model.ElementAt(i).Id.ToString()');"/></div>
                    <p>&#160</p>
                }

                @using (Html.BeginForm("Delete", "NewsAdmin", FormMethod.Post))
                {
                    @Html.HiddenFor(Model => Model.ElementAt(i).Id)
                    <div class="news-del-btn-container"><input type="submit" id="delete-submit" value="X" onclick="return confirm('Вы уверены?') ? true : false;"/></div>
                }
            </div>
        }
    </div>
</div>