FourSeasons/Controllers/Guest/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FourSeasons.Models;
using FourSeasons.dbContexts;

namespace FourSeasons.Controllers.Guest
{
    public class BookingController : Controller
    {
        private readonly FourSeasonsContext _context;
        private BookingVM model;

        public BookingController(FourSeasonsContext context)
        {
            model = new BookingVM();
            _context = context;
        }

        public IActionResult Index()
        {
            model.RoomList = getRooms();
            model.TotalPrice = _context.TotalPriceSet.Find(1).Value;
            _context.TotalPriceSet.Find(1).Value = 0;
            _context.SaveChanges();
            return View(model);
        }


        public IActionResult ChooseAction(Room model, string action, DateTime _startDate, DateTime _finishDate, string _name, string _email)
        {
            if (action == "getCost")
            {
                getCost(model, _startDate, _finishDate);
            }
            else if (action == "Book")
            {
                Book(model, _startDate, _finishDate, _name, _email);
            }

            return RedirectToAction("Index");
        }



        private IActionResult getCost(Room model, DateTime _startDate, DateTime _finishDate)
        {
            _context.TotalPriceSet.Find(1).Value = (int)calculateCost(model, _startDate, _finishDate);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        private double calculateCost(Room model, DateTime _startDate, DateTime _finishDate)
        {
            double cost = 0;
            double seaview = 0;
            double balcon = 0;
            double price = 0;
            double bar = 1500;

            while (!_startDate.Date.Equals(_finishDate.Date))
            {
                switch (model.Type)
                {
                    case "Одноместный": price = 2000; break;
                    case "Двухместный": price = 3500; break;
                    case "Четырехместный": price = 5000; break;
                    case "Мансарда": price = 3000; break;
                }

                if (model.SeaView == true)
                {
                    seaview = price * 0.2;
                }

                if (model.Balcon == true)
                {
                    balcon = price * 0.15;
                }

                cost += price + seaview + balcon;

                _startDate = _startDate.AddDays(1);
            }

            if (model.Bar == true)
            {
                cost += bar;
            }

            return cost;
        }



        private IActionResult Book(Room model, DateTime _startDate, DateTime _finishDate, string _name, string _email)
        {
            _context.BookingSet.Add(new Booking
            {
                Name = _name,
                Email = _email,
                Type = model.Type,
                SeaView = model.SeaView,
                Balcon = model.Balcon,
                Bar = model.Bar,
                TotalPrice = (int)calculateCost(model, _startDate, _finishDate),
                StartDate = _startDate,
                FinishDate = _finishDate
            });

            _context.SaveChanges();
            return RedirectToAction("Index");
        }



        private List<Room> getRooms()
        {
            List<Room> roomsList = new List<Room>();

            foreach (Room element in _context.RoomsSet)
                roomsList.Add(element);

            return roomsList;
        }

        
        
     
    }
}

FourSeasons/Controllers/Guest/ComfortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FourSeasons.Models;
using FourSeasons.dbContexts;

namespace FourSeasons.Controllers.Guest
{
    public class ComfortController : Controller
    {
        private readonly FourSeasonsContext _context;

        public ComfortController(FourSeasonsContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(getComforts());
        }

        private List<Comfort> getComforts()
        {
            List<Comfort> comfortsList = new List<Comfort>();

            foreach (Comfort element in _context.ComfortsSet)
                comfortsList.Add(element);

            return comfortsList;
        }

    }
}

FourSeasons/Controllers/Guest/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FourSeasons.Models;
using FourSeasons.dbContexts;

namespace FourSeasons.Controllers.Guest
{
    public class FoodController : Controller
    {
        private readonly FourSeasonsContext _context;

        public FoodController(FourSeasonsContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(GetFood());
        }

        private List<Food> GetFood()
        {
            List<Food> foodList = new List<Food>();

            foreach (Food element in _context.FoodSet)
                foodList.Add(element);

            return foodList;
        }
    }
}

FourSeasons/Controllers/Guest/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FourSeasons.Models;
using FourSeasons.dbContexts;

namespace FourSeasons.Controllers.Guest
{
    public class RoomsController : Controller
    {
        private readonly FourSeasonsContext _context;

        public RoomsController(FourSeasonsContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(getRooms());
        }

        private List<Room> getRooms()
        {
            List<Room> roomsList = new List<Room>();

            foreach (Room element in _context.RoomsSet)
                roomsList.Add(element);

            return roomsList;
        }
    }
}

FourSeasons/Controllers/Guest/SiteMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FourSeasons.Controllers.Guest
{
    public class SiteMapController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FourSeasons/Views/SiteMap/Index.cshtml
@{
    ViewData["Title"] = "Карта сайта";
}

<link rel="stylesheet" href="~/css/sitemap.css" />

<div class="content">
    <div class="content-food">

        <div class="food-title">
            <p>Карта сайта</p>
        </div>



        <div class="food-list-container">

            <div class="category-container">
                <div class="parent">
                    <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                </div>

                <div class="child">
                    <a asp-area="" asp-controller="Home" asp-action="NewsArchive">Архив новостей</a>
                </div>
            </div>

            <div class="category-container">
                <div class="parent">
                    <a asp-area="" asp-controller="" asp-action="" style="pointer-events: none;">Об отеле</a>
                </div>

                <div class="child">
                    <a asp-area="" asp-controller="Gallery" asp-action="Index">Галерея</a><br />
                    <a asp-area="" asp-controller="Comfort" asp-action="Index">Услуги и удобства</a><br />
                    <a asp-area="" asp-controller="Contacts" asp-action="Index">Контакты</a><br />
                    <a asp-area="" asp-controller="Comments" asp-action="Index">Отзывы</a>
                </div>
            </div>

            <div class="category-container">
                <div class="parent">
                    <a asp-area="" asp-controller="" asp-action="" style="pointer-events: none;">Номера</a>
                </div>

                <div class="child">
                    <a asp-area="" asp-controller="Rooms" asp-action="Index">Просмотр номеров</a><br />
                    <a asp-area="" asp-controller="Booking" asp-action="Index">Бронирование</a>
                </div>
            </div>

            <div class="category-container">
                <div class="parent">
                    <a asp-area="" asp-controller="Food" asp-action="Index">Питание</a>
                </div>

                <div class="category-container">
                    <div class="parent">
                        <a asp-area="" asp-controller="SiteMap" asp-action="Index">Карта сайта</a>
                    </div>





                </div>



            </div>
</div>